// <auto-generated />
namespace MailSender.Lib.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class SchedulerTasks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SchedulerTasks));
        
        string IMigrationMetadata.Id
        {
            get { return "201911011100446_SchedulerTasks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
